feat(flags): add new component
Elonsoft/elonkit-angular2 pull request #18
Opened 2024-04-25 15:42 UTC by BorisNovi

2024-05-06 15:11 UTC, feerzlay requested changes

2024-05-06 15:11 UTC, feerzlay commented on projects/elonkit/src/ui/flag/demo-wrapper/demo-wrapper.component.ts
> +                border: '1px solid rgba(0, 0, 0, 0.08)',
Можно как в реакте демку сделать, без доп. оберток над иконками

2024-05-06 15:11 UTC, feerzlay commented on projects/elonkit/src/ui/flag/flag.stories.ts
> +const meta: Meta<DemoWrapperComponent> = {
Давай добавим `title: 'UI/Flags'`

2024-05-17 15:11 UTC, BorisNovi commented on projects/elonkit/src/ui/flag/flag.component.scss
> +  outline: rgba(0, 0, 0, 0.04) solid 1px;
Ok

2024-05-17 15:15 UTC, BorisNovi commented on projects/elonkit/src/ui/flag/demo-wrapper/demo-wrapper.component.ts
> +                border: '1px solid rgba(0, 0, 0, 0.08)',
Обертка в первую очередь сделана для отображаения пользователю тултипа с кодом флага. Стоит ли убирать удобную функцию?

2024-05-17 15:46 UTC, BorisNovi commented on projects/elonkit/src/ui/flag/flag.stories.ts
> +const meta: Meta<DemoWrapperComponent> = {
Готово

2024-08-02 14:45 UTC, merged