feat(error-page): add new component
Elonsoft/elonkit-angular2 pull request #19
Opened 2024-05-06 13:11 UTC by BorisNovi

2024-05-06 15:25 UTC, feerzlay requested changes

2024-05-06 15:25 UTC, feerzlay commented on projects/elonkit/src/ui/error-page/error-page.component.theme.scss
> +  es-error-page {
Немного смущает использование селектора по элементу, когда в остальных компонентах классы используются

2024-05-06 18:28 UTC, BorisNovi commented on projects/elonkit/src/ui/error-page/error-page.stories.ts
> +      <es-error-page [imageUrl]='imageUrl'>
Так через style мы точно также можем прокинуть background-image. Прочто ничего не вводя в инпут изначально. Да и зачем стлилизовать? Картинка же растягивается по размерам.

2024-05-07 06:57 UTC, BorisNovi commented on projects/elonkit/src/ui/error-page/error-page.stories.ts
> +      <es-error-page [imageUrl]='imageUrl'>
Так тоже работает.
```
<es-error-page style="background-image: url('https://picsum.photos/1000/1200');">
<!-- some tags -->
</es-error-page>
```

2024-05-07 07:11 UTC, BorisNovi commented on projects/elonkit/src/ui/error-page/error-page.component.theme.scss
> +  es-error-page {
Сделал через хостбиндинг

2024-08-02 14:50 UTC, merged