Feat/sidebar
Elonsoft/elonkit-angular2 pull request #25
Opened 2024-06-03 16:27 UTC by BorisNovi

2024-06-05 14:01 UTC, feerzlay requested changes

2024-06-05 14:01 UTC, feerzlay commented on projects/elonkit/src/ui/sidebar/demo-wrapper/demo-wrapper.component.ts
> +                  [inset]="true"></es-sidebar-item>
Там в cdk был механизм, чтобы булевые инпуты можно было просто как аргумент `inset` накидывать (наверно в тултипе есть пример)

2024-06-19 16:25 UTC, BorisNovi commented on projects/elonkit/src/ui/sidebar/demo-wrapper/demo-wrapper.component.ts
> +                  [inset]="true"></es-sidebar-item>
Сделано

2024-06-19 16:25 UTC, BorisNovi commented on projects/elonkit/src/ui/sidebar/sidebar-divider/sidebar-divider.component.html
> +      'es-sidebar-divider__line_primary-color': color === 'primary',
Сделано иначе и там, где требуется

2024-06-19 16:26 UTC, BorisNovi commented on projects/elonkit/src/ui/sidebar/sidebar-item/sidebar-item.component.ts
> +  @Input() color: 'default' | 'primary' | 'secondary' = 'default';
Сделано

2024-06-20 07:23 UTC, BorisNovi commented on projects/elonkit/src/ui/sidebar/sidebar-item/sidebar-item.component.ts
> +  @Input() isExpandClicable = false;
Готово

2024-06-20 07:23 UTC, BorisNovi commented on projects/elonkit/src/utils/resize-height-observer.ts
> +    let height = target.clientHeight;
Отложено

2024-06-20 07:25 UTC, BorisNovi commented on projects/elonkit/src/ui/sidebar/sidebar-item/sidebar-item.component.theme.scss
> +      box-shadow:
Ok

2024-06-20 09:49 UTC, BorisNovi commented on projects/elonkit/src/ui/sidebar/sidebar-toggle/sidebar-toggle.component.ts
> +  @Input() labelOpen = 'Expand';
Готово

2024-08-02 15:07 UTC, merged